; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MinimizeBox -MaximizeBox
Menu FileMenu, Add, &Exit, Exit
Menu MenuBar, Add, &File, :FileMenu
Gui Menu, MenuBar

Gui Add, Progress, x8 y368 w603 h20 -Smooth, 33
Gui Add, Button, x8 y344 w80 h23, &Shrink!
Gui Add, Button, x528 y344 w80 h23, &Cancel
Gui Add, CheckBox, vRemoveEdge x16 y16 w120 h23 +Checked, Remove &Edge
Gui Add, GroupBox, x8 y0 w201 h117, Browsers
Gui Add, CheckBox, vRestoreIE x16 y40 w151 h23 +Checked, Restore &Internet Explorer
Gui Add, CheckBox, x16 y64 w187 h23, &Install Clean Flash Player (for IE)
Gui Add, CheckBox, x16 y88 w120 h23, &Install Firefox
Gui Add, GroupBox, x216 y0 w187 h345, Windows Features
Gui Add, Radio, vClassicTheme x232 y32 w130 h23, Enable &Classic Theme
Gui Add, Radio, x232 y56 w130 h23, &Disable Classic Theme
Gui Add, Radio, x232 y80 w130 h23 +Checked, Ignore Classic Theme
Gui Add, GroupBox, x408 y0 w207 h120, Programming Tools
Gui Add, CheckBox, x416 y40 w72 h23 +Checked, Install AHK
Gui Add, CheckBox, x416 y64 w120 h23 +Checked, Install Python 3
Gui Add, CheckBox, x416 y16 w120 h23 +Checked, Install Node.js
Gui Add, GroupBox, x224 y16 w175 h99, Classic Theme
Gui Add, GroupBox, x224 y120 w173 h118, OEM Info
Gui Add, Radio, x232 y136 w120 h23, Clear OEM Info
Gui Add, Radio, x232 y160 w155 h23, Use Shrinkdows OEM Info
Gui Add, Radio, x232 y184 w154 h23, Use Custom OEM Info
Gui Add, Radio, x232 y208 w152 h23 +Checked, Don't Change OEM Info
Gui Add, CheckBox, x224 y240 w120 h23 +Checked, Remove UWP Apps
Gui Add, CheckBox, x224 y264 w105 h35 +Checked, Remove Misc. Unnecessary Junk
Gui Add, CheckBox, x224 y296 w169 h23 +Checked, Run AIO Framework Setup
Gui Add, CheckBox, x16 y136 w195 h23 +Checked, Install Choco + Choco GUI
Gui Add, GroupBox, x8 y120 w200 h156, Programs
Gui Add, CheckBox, x16 y160 w177 h23 +Checked, Install Winaero Tweaker
Gui Add, CheckBox, x16 y184 w182 h23 +Checked, Install Windows Toolbox
Gui Add, CheckBox, x416 y88 w120 h23 +Checked, Install Powershell 7
Gui Add, GroupBox, x408 y120 w207 h131, About
Gui Add, Picture, x520 y160 w64 h55, C:\Users\Daniel\Documents\Projects\Logo3.png
Gui Add, Picture, x424 y136 w96 h96, C:\Users\Daniel\Downloads\ezgif.com-gif-maker (2).png
Gui Add, Link, x416 y224 w193 h23, Shrinkdows by <a href="https://1justjoey.github.io/MyWebsiteHosting/">Just Joey</a> and <a href="https://tinyurl.com/techstuffyt">Tech Stuff</a>
Gui Add, CheckBox, x224 y320 w120 h23, Run DISM + SFC
Gui Add, CheckBox, x16 y208 w176 h33, Install Windows 7, Vista, and XP games
Gui Add, CheckBox, x16 y240 w191 h33, Install Simon Tatham's Portable Puzzle Collection

Gui Show, w620 h392, Shrinkdows
Return

Exit:
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }

Return

GuiEscape:
GuiClose:
    ExitApp
