; Generated by AutoGUI 2.6.2
;@Ahk2Exe-SetMainIcon appicon.ico
#NoTrayIcon
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MinimizeBox -MaximizeBox
Menu FileMenu, Add, &Exit, Exit
Menu MenuBar, Add, &File, :FileMenu
Gui Menu, MenuBar

FileInstall, Logo3.png, %A_Temp%\Logo3.png
FileInstall, Joey.png, %A_Temp%\Joey.png

Gui Add, Progress, vProg x8 y368 w603 h20 -Smooth, 0
Gui Add, Button, vShrink gStart x8 y344 w80 h23, &Shrink!
Gui Add, Button, vCancel gExit x528 y344 w80 h23, &Cancel
Gui Add, CheckBox, vRemoveEdge x16 y16 w120 h23 +Checked, Remove &Edge
Gui Add, GroupBox, x8 y0 w201 h117, Browsers
Gui Add, CheckBox, vRestoreIE x16 y40 w151 h23 +Checked, Restore &Internet Explorer
Gui Add, CheckBox, vFlashPlayer x16 y64 w187 h23, &Install Clean Flash Player (for IE)
Gui Add, CheckBox, vFirefox x16 y88 w120 h23, &Install Firefox
Gui Add, GroupBox, x216 y0 w187 h345, Windows Features
Gui Add, Radio, vEnableClassicTheme x232 y32 w130 h23, Enable &Classic Theme
Gui Add, Radio, vDisableClassicTheme x232 y56 w130 h23, &Disable Classic Theme
Gui Add, Radio, vIgnoreClassicTheme x232 y80 w130 h23 +Checked, Ignore Classic Theme
Gui Add, GroupBox, x408 y0 w207 h120, Programming Tools
Gui Add, CheckBox, vAHK x416 y40 w72 h23 +Checked, Install AHK
Gui Add, CheckBox, vPython x416 y64 w120 h23 +Checked, Install Python 3
Gui Add, CheckBox, vNodeJS x416 y16 w120 h23 +Checked, Install Node.js
Gui Add, GroupBox, x224 y16 w175 h99, Classic Theme
Gui Add, GroupBox, x224 y120 w173 h118, OEM Info
Gui Add, Radio, vClearOEMInfo x232 y136 w120 h23, Clear OEM Info
Gui Add, Radio, vMyOEMInfo x232 y160 w155 h23, Use Shrinkdows OEM Info
Gui Add, Radio, vCustomOEMInfo x232 y184 w154 h23, Use Custom OEM Info
Gui Add, Radio, vNoOEMInfo x232 y208 w152 h23 +Checked, Don't Change OEM Info
Gui Add, CheckBox, vNoUWP x224 y240 w120 h23 +Checked, Remove UWP Apps
Gui Add, CheckBox, vMiscJunk x224 y264 w120 h36 +Checked, Remove Misc. Unnecessary Junk
Gui Add, CheckBox, vFrameworks x224 y296 w169 h23 +Checked, Run AIO Framework Setup
Gui Add, CheckBox, vChoco x16 y136 w195 h23 +Checked, Install Choco + Choco GUI
Gui Add, GroupBox, x8 y120 w200 h156, Programs
Gui Add, CheckBox, vWinaero x16 y160 w177 h23 +Checked, Install Winaero Tweaker
Gui Add, CheckBox, vWindowsToolbox x16 y184 w182 h23 +Checked, Install Windows Toolbox
Gui Add, CheckBox, vPS7 x416 y88 w120 h23 +Checked, Install Powershell 7
Gui Add, GroupBox, x408 y120 w207 h131, About
Gui Add, Picture, x520 y160 w64 h55, %A_Temp%\Logo3.png
Gui Add, Picture, x424 y136 w96 h96, %A_Temp%\Joey.png
Gui Add, Link, x416 y224 w193 h23, Shrinkdows by <a href="https://1justjoey.github.io/MyWebsiteHosting/">Just Joey</a> and <a href="https://tinyurl.com/techstuffyt">Tech Stuff</a>
Gui Add, CheckBox, vDISM x224 y320 w120 h23 +Checked, Run DISM + SFC
Gui Add, CheckBox, vWinGames x16 y208 w176 h33 +Checked, Install Windows 7, Vista, and XP games
Gui Add, CheckBox, vPuzzlePack x16 y240 w191 h33 +Checked, Install Simon Tatham's Portable Puzzle Collection

Gui Show, w620 h392, Shrinkdows
Return

Exit:
GuiEscape:
GuiClose:
    ExitApp

Start:
Gui, Submit, NoHide
GuiControl, +Disabled, Cancel
GuiControl, +Disabled, Shrink
GuiControl, +Disabled, DISM
GuiControl, +Disabled, WindowsToolbox
GuiControl, +Disabled, Winaero
GuiControl, +Disabled, PS7
GuiControl, +Disabled, Choco
GuiControl, +Disabled, Frameworks
GuiControl, +Disabled, MiscJunk
GuiControl, +Disabled, NoUWP
GuiControl, +Disabled, ClearOEMInfo
GuiControl, +Disabled, MyOEMInfo
GuiControl, +Disabled, CustomOEMInfo
GuiControl, +Disabled, NoOEMInfo
GuiControl, +Disabled, Firefox
GuiControl, +Disabled, NodeJS
GuiControl, +Disabled, Python
GuiControl, +Disabled, AHK
GuiControl, +Disabled, EnableClassicTheme
GuiControl, +Disabled, DisableClassicTheme
GuiControl, +Disabled, IgnoreClassicTheme
GuiControl, +Disabled, RemoveEdge
GuiControl, +Disabled, RestoreIE
GuiControl, +Disabled, FlashPlayer
GuiControl, +Disabled, WinGames
GuiControl, +Disabled, PuzzlePack

if (WinGames) {
  UrlDownloadToFile, https://bluepload.unstable.life/selif/xp-gamesfor-w7.exe, %A_Temp%\xp.exe
  RunWait, "%A_Temp%\xp.exe" -s1
  FileDelete, %A_Temp%\xp.exe
  UrlDownloadToFile, https://win7games.com/download/Windows7Games_for_Windows_11_10_8.zip, %A_Temp%\w7.exe
  RunWait, "%A_Temp%\w7.exe" /S
  FileDelete, %A_Temp%\w7.exe
  UrlDownloadToFile, https://bluepload.unstable.life/selif/holdem-inkball-tinker-setup.exe, %A_Temp%\wVista.exe
  RunWait, "%A_Temp%\wVista.exe" /S
  FileDelete, %A_Temp%\wVista.exe
}

if (Choco) {
  RunWait, powershell -ep bypass -c [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));choco install ChocolateyGUI
}

if (PuzzlePack) {
  UrlDownloadToFile, https://www.chiark.greenend.org.uk/~sgtatham/puzzles/puzzles-installer.msi, %A_Temp%\PuzzlePack.msi
  RunWait, msiexec /passive /qb /norestart /i "%A_Temp%\PuzzlePack.msi"
  FileDelete, %A_Temp%\PuzzlePack.msi
}

GuiControl,,Prog,100
GuiControl,, Cancel, &Close
GuiControl, -Disabled, Cancel
Return
